
services:
  neo4j:
    image: neo4j:5-enterprise
    container_name: epansa-neo4j
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474" # HTTP port
      - "7687:7687" # Bolt port
    restart: unless-stopped


volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: